Add generalized crossplatform support for Hyperion serializer.
akkadotnet/akka.net pull request #4878
Opened 2021-03-26 23:27 UTC by Arkatufus

2021-03-26 23:27 UTC, Arkatufus commented
Need to wait for a new Hyperion changes first.

2021-04-01 14:17 UTC, Aaronontheweb commented
@Arkatufus those new Hyperion changes are ready now, yes?

2021-04-09 14:09 UTC, Arkatufus commented
They are ready, but they're not merged yet. These changes would need the new Hyperion nuget package.

2021-04-14 01:35 UTC, Arkatufus commented
Ok, this is ready for review.

2021-04-14 18:36 UTC, Aaronontheweb requested changes
LGTM, but need to add some user-facing documentation to here: https://github.com/akkadotnet/akka.net/blob/dev/docs/articles/networking/serialization.md#how-to-setup-hyperion-as-default-serializer

2021-04-14 18:37 UTC, Aaronontheweb commented on src/contrib/serializers/Akka.Serialization.Hyperion/HyperionSerializerSetup.cs
> +﻿using System;
Need to add copyright header

2021-04-14 18:38 UTC, Aaronontheweb commented on src/contrib/serializers/Akka.Serialization.Hyperion/HyperionSerializerSetup.cs
> +        public readonly Option<bool> PreserveObjectReferences;
Make these properties rather than fields

2021-04-19 22:30 UTC, Aaronontheweb approved these changes
LGTM

2021-04-19 22:57 UTC, merged