Ported DivertTo combinator
akkadotnet/akka.net pull request #5137
Opened 2021-07-09 06:31 UTC by ismaelhamed

Port [#24310](https://github.com/akka/akka/pull/24310)

2021-07-13 14:53 UTC, Aaronontheweb requested changes
Need to add some docs for this on the "built in stages" page for Akka.Streams docs

2021-07-13 14:53 UTC, Aaronontheweb commented on src/core/Akka.Streams/Dsl/FlowOperations.cs
> +        /// will be sent to the <seealso cref="Sink{TIn,TMat}"/> instead of being passed through if the predicate `when` returns `true`.
Makes sense

2021-07-14 06:18 UTC, ismaelhamed commented
Updated documentation with a brief description

2021-07-14 14:45 UTC, Aaronontheweb approved these changes

2021-07-14 15:17 UTC, merged