Fix Dns.Resolve issue by using ContinueWith and AggregateException.Flatten
akkadotnet/akka.net pull request #5260
Opened 2021-09-06 18:06 UTC by Arkatufus

Closes #5154

2021-09-06 18:52 UTC, Aaronontheweb requested changes
One small bug that needs to be addressed

2021-09-06 18:52 UTC, Aaronontheweb commented on src/core/Akka/IO/InetAddressDnsResolver.cs
> +                }, TaskContinuationOptions.ExecuteSynchronously).PipeTo(Sender);
Need to close over `Sender` here

2021-09-06 19:06 UTC, Arkatufus commented on src/core/Akka/IO/InetAddressDnsResolver.cs
> +                }, TaskContinuationOptions.ExecuteSynchronously).PipeTo(Sender);
Done

2021-09-06 19:14 UTC, Aaronontheweb approved these changes
LGTM

2021-09-06 20:59 UTC, Aaronontheweb commented
Some of your own tests on this PR are failing

2021-09-07 14:05 UTC, Aaronontheweb commented on src/core/Akka/IO/InetAddressDnsResolver.cs
> +                                _cache.Put(newAnswer, _negativeTtl);
Don't cache failures, since they can be intermittent

2021-09-07 14:15 UTC, Aaronontheweb requested changes
Need to handle all DNS exceptions and not cache failures

2021-09-07 16:22 UTC, Aaronontheweb requested changes
Have an API change in here that we probably can leave alone - it's minor, but the API approval tests are failing

2021-09-07 16:22 UTC, Aaronontheweb commented on src/core/Akka/IO/Dns.cs
> +            public IImmutableList<IPAddress> Ipv6 { get; }
This is a public API change - may as well leave it as `IEnumerable`

2021-09-07 19:37 UTC, Arkatufus commented on src/core/Akka/IO/Dns.cs
> +            public Exception Exception { get; }
Need to add this new property to pass back exceptions from failed DNS resolve call

2021-09-07 19:38 UTC, Arkatufus commented on src/core/Akka/IO/Dns.cs
> +                        ExceptionDispatchInfo.Capture(Exception).Throw();
Failed DNS resolve exception is being rethrown here

2021-09-07 21:30 UTC, merged