harden `ClusterLogSpec`
akkadotnet/akka.net pull request #6031
Opened 2022-07-04 19:46 UTC by Aaronontheweb

## Changes

The `JoinAsync` method wasn't written correctly - need to force `JoinAsync` to run to completion for assertion to make any kind of sense.

2022-07-05 16:31 UTC, Arkatufus commented on src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
> +                    .ExpectOneAsync(async () => await _cluster.JoinAsync(_selfAddress).ShouldCompleteWithin(Remaining));
I have little trust that the `JoinAsync` method is actually correct. I think we should use a more manual way of asserting this, like the one you've implemented in the `DownAsync` method below.

2022-07-05 16:31 UTC, Arkatufus requested changes
Just a slight change needed

2022-07-06 16:45 UTC, Aaronontheweb commented on src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
> +                    .ExpectOneAsync(async () => await _cluster.JoinAsync(_selfAddress).ShouldCompleteWithin(Remaining));
Will do

2022-07-11 14:40 UTC, Aaronontheweb commented on src/core/Akka.Cluster.Tests/ClusterLogSpec.cs
> +                    .ExpectOneAsync(async () => await _cluster.JoinAsync(_selfAddress).ShouldCompleteWithin(Remaining));
Done

2022-07-12 16:38 UTC, Arkatufus approved these changes
LGTM

2022-07-12 21:54 UTC, merged