`Exception` serialization support for built-in messages
akkadotnet/akka.net pull request #6297
Opened 2022-12-08 02:19 UTC by Aaronontheweb

## Changes

Fixes #3903 

Adding support to any built-in messages that support `Exception` types. Won't be adding any serialization magic to Newtonsoft.Json for exception handling as that starts to get into CVE territory given the deep amount of context the serialization payloads contain. 

Some of the designs we're considering for 1.5 / later, namely using source generators to create compile-time serialization for everything, will make this issue easier to manage in the future. For now I think it's good to preserve the location transparency of Akka.NET's own built-in messages for end-user convenience and consistency.

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [ ] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [ ] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [ ] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).
* [ ] Design discussion issue #3903
* [ ] Changes in public API reviewed, if any.
* [ ] I have added website documentation for this feature.

2022-12-08 03:05 UTC, Aaronontheweb reviewed
Detailed my changes

2022-12-08 03:05 UTC, Aaronontheweb commented on src/core/Akka.Remote.Tests/Serialization/MiscMessageSerializerSpec.cs
> +        public void Can_serialize_StatusSuccess(object payload)
Try with a variety of payloads for `Status.Success`

2022-12-08 20:21 UTC, Arkatufus requested changes
Looks good overall, got a question.

2022-12-08 20:21 UTC, Arkatufus commented on src/core/Akka.Remote/Configuration/Remote.conf
> +      "Akka.Actor.Status+Failure, Akka" = akka-misc
Can't we still use feature flags if we programmatically inject these bindings using `Serialization.AddSerializationMap()`?

2022-12-08 20:24 UTC, Aaronontheweb commented on src/core/Akka.Remote/Configuration/Remote.conf
> +      "Akka.Actor.Status+Failure, Akka" = akka-misc
I sincerely don't think the juice is worth the squeeze to do it, especially given that 1.5 is just around the corner.

2022-12-08 20:25 UTC, Arkatufus approved these changes

2022-12-08 20:33 UTC, Arkatufus commented on src/core/Akka.Remote/Configuration/Remote.conf
> +      "Akka.Actor.Status+Failure, Akka" = akka-misc
Good point

2022-12-08 23:01 UTC, Zetanova commented
@Aaronontheweb The issue itself is not addressed.
If the remote actor throws a unknown exception type or inner-exception 
back to the caller. The caller will not receive it. 

The remote actor itself does not know or better to say should not to know 
because everything is "transparent"

The current effect is that the remote connection will fail with a deserializing exception 
and the caller will never see a response message.
In a cluster this would lead to a disassociation and a required restart of the node.

2022-12-08 23:16 UTC, Zetanova commented
@Aaronontheweb 

https://github.com/akkadotnet/akka.net/blob/fbc338a63fcbc8376a6f88a421247c6b2c77a743/src/core/Akka.Remote/Serialization/ExceptionSupport.cs#L109-L127

This method should only TryToDeserialize if the TypeName can be resolved.
If not a `AkkaGenericException` should be created

My Idea was to replace the `Exception` instance to a basic `Reason` instance on the producing actor.
It can be tagged by an Id and stored into a memory cache or something else defined by the users config (like elasticsearch)

For the receiver it would the be OPTIONAL to convert `Reason` back to an `Exception` instance
and this could always be over an `TryConvertReasonToException` pattern.

2022-12-08 23:53 UTC, Aaronontheweb commented
> @Aaronontheweb The issue itself is not addressed. If the remote actor throws a unknown exception type or inner-exception back to the caller. The caller will not receive it.
> 
> The remote actor itself does not know or better to say should not to know because everything is "transparent"

We're not going to recursively nest exceptions all the way down the stack - sorry, but we have to draw the line somewhere. We don't want to be in the already messy business + dangerous of serializing exceptions.

> The current effect is that the remote connection will fail with a deserializing exception and the caller will never see a response message. In a cluster this would lead to a disassociation and a required restart of the node.

This is not true - Akka.Remote does not drop associations when deserialization exceptions occur. That's been fixed a ways back.

2022-12-08 23:53 UTC, merged

2022-12-09 01:55 UTC, Zetanova commented
> We're not going to recursively nest exceptions all the way down the stack - sorry, but we have to draw the line somewhere. We don't want to be in the already messy business + dangerous of serializing exceptions.

My proposal to convert the exceptions to basic Reason messages is exactly the opposite.
This would already happen in the `PostStop` of the `ActorBase` and then escalated. 

The Serializer/Wire would in the **default config** then **never see a single exception**.
The conversion back to an exception would be then optional and more or less for legacy use
and supported only with an extensions.

Instead of a simple `Reason` type an `AkkaGenericException` could be made.
It should only be a `WellKnown` type for all nodes and could hold an `Error-Guid`, `Error-Code` and `Error-Message` 
and **never** a single `InnerException`

2022-12-09 14:08 UTC, Aaronontheweb commented
> The Serializer/Wire would in the default config then never see a single exception.
The conversion back to an exception would be then optional and more or less for legacy use
and supported only with an extensions.

So we don't have a formal spec for this yet as we think it's out of scope for Akka.NET v1.5, but we're looking at replacing the "DIY" serialization system with something more authoritative (source generators) in the future. We'd have a formula for working with Exception types as part of that most likely.