Fix persistence allocations #5505.
akkadotnet/akka.net pull request #6384
Opened 2023-02-04 21:23 UTC by F0b0s

Fixes #

## Changes

As discussed in #5505 closure object creation for `WithCircuitBreaker<TResult>` was fixed. Also all local functions like `ProcessResults`, `ExecuteBatch`, `Resequence` was moved into class method because every call ends with closure object creation. 
For `AtomicWrite` linq methods was removed usage because it ends in memory allocation.
It shows good consumed memory performance for write journal critical path:
`JournalWriteBenchmarks`  - 4% lower.
`AtomicWriteBenchmark` - 25% lower

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

### Latest `dev` Benchmarks 

JournalWriteBenchmarks

|             Method | PersistentActors | WriteMsgCount |        Mean |     Error |   StdDev |      Gen0 |      Gen1 |   Allocated |
|------------------- |----------------- |-------------- |------------:|----------:|---------:|----------:|----------:|------------:|
| WriteToPersistence |                1 |           100 |    789.1 us |  47.17 us | 133.8 us |         - |         - |   163.88 KB |
| WriteToPersistence |               10 |           100 |  1,868.0 us |  50.21 us | 145.7 us |         - |         - |  1582.23 KB |
| WriteToPersistence |              100 |           100 | 24,981.2 us | 492.14 us | 657.0 us | 2000.0000 | 1000.0000 | 15686.82 KB |

AtomicWriteBenchmark

|      Method | WriteMsgCount |     Mean |     Error |    StdDev |      Gen0 | Allocated |
|------------ |-------------- |---------:|----------:|----------:|----------:|----------:|
| Constructor |        100000 | 9.324 ms | 0.1661 ms | 0.2434 ms | 1000.0000 |   8.39 MB |

### This PR's Benchmarks

InJournalWriteBenchmarks

|             Method | PersistentActors | WriteMsgCount |        Mean |     Error |   StdDev |      Median |      Gen0 |      Gen1 |   Allocated |
|------------------- |----------------- |-------------- |------------:|----------:|---------:|------------:|----------:|----------:|------------:|
| WriteToPersistence |                1 |           100 |    785.2 us |  50.09 us | 143.7 us |    756.2 us |         - |         - |   156.91 KB |
| WriteToPersistence |               10 |           100 |  1,811.6 us |  54.72 us | 157.9 us |  1,765.2 us |         - |         - |  1518.79 KB |
| WriteToPersistence |              100 |           100 | 23,806.4 us | 463.65 us | 694.0 us | 23,761.8 us | 2000.0000 | 1000.0000 | 14953.15 KB |

AtomicWriteBenchmark

|      Method | WriteMsgCount |     Mean |     Error |    StdDev |      Gen0 | Allocated |
|------------ |-------------- |---------:|----------:|----------:|----------:|----------:|
| Constructor |        100000 | 8.652 ms | 0.1305 ms | 0.2031 ms | 1000.0000 |    6.1 MB |

2023-02-05 19:15 UTC, F0b0s commented
I can try to rewrite it with local functions as it was earlier, up to you @Aaronontheweb

2023-02-05 19:18 UTC, Aaronontheweb commented
> I can try to rewrite it with local functions as it was earlier, up to you @Aaronontheweb

I'll take a look at this as soon as I can!

BTW, I recommend that you join the Akka.NET Discord and join the #contributors room  - we kick around ideas in there every day usually. https://discord.gg/GSCfPwhbWP

2023-02-09 02:22 UTC, Aaronontheweb approved these changes
LGTM

2023-02-09 02:22 UTC, Aaronontheweb commented on src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
> +                        state.awj.DeleteMessagesToAsync(state.message.PersistenceId, state.message.ToSequenceNr));
lgtm

2023-02-09 02:22 UTC, Aaronontheweb commented on src/core/Akka.Persistence/Journal/AsyncWriteJournal.cs
> +                        state.awj.ReadHighestSequenceNrAsync(state.message.PersistenceId, state.readHighestSequenceNrFrom));
lgtm

2023-02-09 03:21 UTC, Aaronontheweb requested changes
Both sets of multi-node specs are failing using Akka.Persistence + Cluster.Sharding on this PR, which makes me think this change has some unintended side effects. Needs to be investigated and resolved before we can merge.

2023-02-09 06:03 UTC, F0b0s commented
Ok, will take a look.

2023-02-11 19:38 UTC, F0b0s commented
Found an error in my PR,
source code was like:
`                var prepared = PreparePersistentBatch(message.Messages).ToArray();`
i changed it to 
`                var prepared = PreparePersistentBatch(message.Messages);`
and as result of `PreparePersistentBatch` is `IEnumerable`, ToArray play role of materializer, i return it back and all tests are passed.

@Aaronontheweb can you take a look again.

Current benchmark values:
|             Method | PersistentActors | WriteMsgCount |        Mean |     Error |   StdDev |      Gen0 |      Gen1 |   Allocated |
|------------------- |----------------- |-------------- |------------:|----------:|---------:|----------:|----------:|------------:|
| WriteToPersistence |                1 |           100 |    861.3 us |  54.74 us | 157.9 us |         - |         - |   159.08 KB |
| WriteToPersistence |               10 |           100 |  1,754.1 us |  37.88 us | 106.8 us |         - |         - |  1519.92 KB |
| WriteToPersistence |              100 |           100 | 24,152.2 us | 480.19 us | 571.6 us | 2000.0000 | 1000.0000 | 15190.59 KB |

2023-02-11 22:18 UTC, F0b0s commented
And i rewrited linq calls in `WriteJournalBase` and memory allocation decreased on 10% percent in `JournalWriteBenchmarks`

|             Method | PersistentActors | WriteMsgCount |        Mean |     Error |   StdDev |      Gen0 |      Gen1 |   Allocated |
|------------------- |----------------- |-------------- |------------:|----------:|---------:|----------:|----------:|------------:|
| WriteToPersistence |                1 |           100 |    805.2 us |  49.43 us | 141.8 us |         - |         - |   149.81 KB |
| WriteToPersistence |               10 |           100 |  1,699.2 us |  43.27 us | 124.1 us |         - |         - |  1423.88 KB |
| WriteToPersistence |              100 |           100 | 22,949.3 us | 457.68 us | 685.0 us | 2000.0000 | 1000.0000 | 14178.66 KB |

2023-02-14 15:15 UTC, Aaronontheweb commented
I'll re-check the numbers of my machine and give you some feedback

2023-02-14 17:52 UTC, Aaronontheweb commented
On my Ryzen machine.

## `dev`

``` ini

BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19044.2486/21H2/November2021Update)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.100
  [Host]     : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
  Job-JKMUOM : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2

InvocationCount=1  UnrollFactor=1  

```
|             Method | PersistentActors | WriteMsgCount |        Mean |     Error |     StdDev |      Gen0 |      Gen1 |   Allocated |
|------------------- |----------------- |-------------- |------------:|----------:|-----------:|----------:|----------:|------------:|
| **WriteToPersistence** |                **1** |           **100** |    **502.9 μs** |  **47.25 μs** |   **137.1 μs** |         **-** |         **-** |   **164.11 KB** |
| **WriteToPersistence** |               **10** |           **100** |  **1,881.5 μs** | **194.93 μs** |   **565.5 μs** |         **-** |         **-** |  **1578.97 KB** |
| **WriteToPersistence** |              **100** |           **100** | **31,122.9 μs** | **690.19 μs** | **1,854.1 μs** | **2000.0000** | **1000.0000** | **15608.03 KB** |


## This PR

``` ini

BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19044.2486/21H2/November2021Update)
AMD Ryzen 7 1700, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.100
  [Host]     : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
  Job-DUCEDZ : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2

InvocationCount=1  UnrollFactor=1  

```
|             Method | PersistentActors | WriteMsgCount |        Mean |     Error |     StdDev |      Median |      Gen0 |      Gen1 |   Allocated |
|------------------- |----------------- |-------------- |------------:|----------:|-----------:|------------:|----------:|----------:|------------:|
| **WriteToPersistence** |                **1** |           **100** |    **464.1 μs** |  **37.16 μs** |   **109.0 μs** |    **479.8 μs** |         **-** |         **-** |   **148.86 KB** |
| **WriteToPersistence** |               **10** |           **100** |  **1,610.2 μs** | **190.79 μs** |   **559.6 μs** |  **1,525.0 μs** |         **-** |         **-** |  **1422.73 KB** |
| **WriteToPersistence** |              **100** |           **100** | **29,956.3 μs** | **852.72 μs** | **2,348.6 μs** | **29,288.3 μs** | **2000.0000** | **1000.0000** | **14044.73 KB** |

2023-02-14 17:54 UTC, Aaronontheweb approved these changes
LGTM

2023-02-14 19:03 UTC, merged