[32-74] `FlowSplitWhenSpec`
akkadotnet/akka.net pull request #6579
Opened 2023-03-25 12:10 UTC by eaba

## Changes

- Change `AssertAllStagesStopped` to `AssertAllStagesStoppedAsync`

2023-04-05 16:58 UTC, Aaronontheweb requested changes
Looks like there are some specs that aren't using the `async` methods yet

2023-04-05 16:58 UTC, Aaronontheweb commented on src/core/Akka.Streams.Tests/Dsl/FlowSplitWhenSpec.cs
> +                        s1.ExpectNext(1);
Don't all of these need to be `async` calls @eaba ?

2023-04-05 17:03 UTC, eaba commented on src/core/Akka.Streams.Tests/Dsl/FlowSplitWhenSpec.cs
> +                        s1.ExpectNext(1);
Ok. Let me check it out

2023-04-05 17:15 UTC, eaba commented on src/core/Akka.Streams.Tests/Dsl/FlowSplitWhenSpec.cs
> +                        s1.ExpectNext(1);
Done

2023-04-05 17:28 UTC, Aaronontheweb approved these changes, later dismissed
LGTM

2023-04-05 17:30 UTC, eaba commented
This is the problem I'm having here `SplitWhen_must_work_in_the_happy_case` @Aaronontheweb 

![image](https://user-images.githubusercontent.com/8049896/230157687-b16f44b4-6094-45dc-a747-d0f64e6f6a2a.png)

2023-04-05 17:54 UTC, Aaronontheweb commented
> This is the problem I'm having here `SplitWhen_must_work_in_the_happy_case` @Aaronontheweb
> 
> ![image](https://user-images.githubusercontent.com/8049896/230157687-b16f44b4-6094-45dc-a747-d0f64e6f6a2a.png)

You'll need to find a way to work the problem

2023-04-06 12:27 UTC, Aaronontheweb commented
There are errors with these tests but the test runner crashed while trying to report on the results. 

```
[xUnit.net 00:06:41.05]       Racy on Azure DevOps
  Passed Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.SplitWhen_must_support_cancelling_the_master_stream [109 ms]
  Passed Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.SplitWhen_must_fail_stream_if_substream_not_materialized_in_time [1 s]
  Skipped Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.SplitWhen_must_resume_stream_when_splitWhen_function_throws [1 ms]
  Passed Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.SplitWhen_must_pass_along_early_cancellation [124 ms]
  Passed Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.SplitWhen_must_work_with_single_element_splits [107 ms]
  Skipped Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.SplitWhen_must_fail_substream_if_materialized_twice [1 ms]
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Xunit.Sdk.TrueException: Failed: Expected no messages during 00:00:00.1000000, instead we received <TestSubscriber.OnError(Processor actor [[akka://FlowSplitWhenSpec-1140/user/StreamSupervisor-1753/Flow-0-0-unknown-operation#1873049784]] terminated abruptly)> from [akka://FlowSplitWhenSpec-1140/user/StreamSupervisor-1753/Flow-0-0-unknown-operation#1873049784] after 00:00:00.0157833
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in D:\a\1\s\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 26
   at Akka.TestKit.TestKitBase.InternalExpectNoMsgAsync(TimeSpan duration, CancellationToken cancellationToken) in D:\a\1\s\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 535
   at Akka.TestKit.TestKitBase.ExpectNoMsgAsync(TimeSpan duration, CancellationToken cancellationToken) in D:\a\1\s\src\core\Akka.TestKit\TestKitBase_Expect.cs:line 501
   at Akka.Streams.TestKit.TestSubscriber.ManualProbe`1.ExpectNoMsgAsync(TimeSpan remaining, CancellationToken cancellationToken) in D:\a\1\s\src\core\Akka.Streams.TestKit\TestSubscriber.cs:line 239
   at Akka.Streams.Tests.Dsl.FlowSplitWhenSpec.<SplitWhen_must_work_in_the_happy_case>b__6_1(ManualProbe`1 masterSubscriber, ISubscription masterSubscription, Func`1 getSubFlow) in D:\a\1\s\src\core\Akka.Streams.Tests\Dsl\FlowSplitWhenSpec.cs:line 96
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

It's the "happy case" spec that's failing again.

2023-04-06 12:33 UTC, eaba commented
Yes, only local! The problem here `ExpectNoMsgAsync`s `TestSubscriber.OnError`

2023-04-07 14:04 UTC, Aaronontheweb approved these changes
LGTM

2023-04-07 14:04 UTC, merged