[54-74] `LazySinkSpec`
akkadotnet/akka.net pull request #6601
Opened 2023-03-25 21:40 UTC by eaba

## Changes

- Change `AssertAllStagesStopped` to `AssertAllStagesStoppedAsync`

2023-03-30 14:16 UTC, eaba commented on src/core/Akka.Streams.Tests/Dsl/LazySinkSpec.cs
> +                //I CHECK IT THIS IS NOT GOOD - EVERYTHING WORKS FINE NOW
//I CHECK IT THIS IS NOT GOOD - EVERYTHING WORKS FINE NOW

2023-04-03 15:06 UTC, Aaronontheweb requested changes
Needs some cleanup but otherwise looks good

2023-04-03 15:06 UTC, Aaronontheweb commented on src/core/Akka.Streams.Tests/Dsl/LazySinkSpec.cs
> +                //I CHECK IT THIS IS NOT GOOD - EVERYTHING WORKS FINE NOW
Please remove any comments that aren't functional

2023-04-04 12:06 UTC, Aaronontheweb approved these changes
LGTM

2023-04-04 12:06 UTC, merged