[WARNING] CS0628: `new protected member declared in sealed type`
akkadotnet/akka.net pull request #6626
Opened 2023-03-28 12:03 UTC by eaba

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

2023-03-28 13:04 UTC, eaba commented on src/core/Akka.Remote/Endpoint.cs
> +        EndpointAssociationException(SerializationInfo info, StreamingContext context)
I have removed that `protected` @Aaronontheweb

2023-03-28 13:04 UTC, eaba commented on src/core/Akka.Remote/Endpoint.cs
> +        OversizedPayloadException(SerializationInfo info, StreamingContext context)
I have removed that `protected` @Aaronontheweb

2023-03-28 13:04 UTC, eaba commented on src/core/Akka.Streams/ActorMaterializer.cs
> +        AbruptStageTerminationException(SerializationInfo info, StreamingContext context) : base(info, context) { }
I have removed that `protected` @Aaronontheweb

2023-03-28 13:04 UTC, eaba commented on src/core/Akka.Streams/Dsl/Graph.cs
> +        PartitionOutOfBoundsException(SerializationInfo info, StreamingContext context) : base(info, context) { }
I have removed that `protected` @Aaronontheweb

2023-03-28 13:04 UTC, eaba commented on src/core/Akka.Streams/Dsl/Tcp.cs
> +        TcpIdleTimeoutException(SerializationInfo info, StreamingContext context) : base(info, context) { }
I have removed that `protected` @Aaronontheweb

2023-03-28 13:04 UTC, eaba commented on src/core/Akka/Actor/Scheduler/SchedulerException.cs
> +        SchedulerException(SerializationInfo info, StreamingContext context)
I have removed that `protected` @Aaronontheweb

2023-03-28 13:05 UTC, eaba commented on src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Net.verified.txt
> -        protected PartitionOutOfBoundsException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
removed @Aaronontheweb

2023-03-28 13:05 UTC, eaba commented on src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveStreams.Net.verified.txt
> -        protected AbruptStageTerminationException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
removed @Aaronontheweb

2023-03-28 13:06 UTC, eaba commented on src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
> -        protected SchedulerException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
removed @Aaronontheweb

2023-03-28 13:07 UTC, eaba reviewed
@Aaronontheweb changes

2023-03-28 17:46 UTC, Aaronontheweb requested changes
Need the serialization constructors back, so make them `public` instead

2023-03-28 17:46 UTC, Aaronontheweb commented on src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.DotNet.verified.txt
> -        protected SchedulerException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
I think that needs to be made public, probably

2023-03-28 17:46 UTC, Aaronontheweb commented on src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCore.Net.verified.txt
> -        protected SchedulerException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) { }
Make all of these public

2023-03-29 01:09 UTC, eaba commented
Changes to `public` @Aaronontheweb

2023-03-30 16:50 UTC, Aaronontheweb approved these changes

2023-03-30 16:50 UTC, merged