enable `keep-majority` default SBR
akkadotnet/akka.net pull request #6628
Opened 2023-03-30 16:44 UTC by Aaronontheweb

## Changes

Enables `keep-majority` as the default SBR and turns it on by default for Akka.Cluster. This was a planned change for Akka.NET v1.5.0 but we didn't implement it.

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).
* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

2023-03-30 16:44 UTC, Aaronontheweb commented
I think I need to write some updates to the documentation and a release advisory for this change as well

2023-03-30 16:56 UTC, Aaronontheweb commented
Looks like I need to update the `DowningProviderSpec` as well

2023-04-04 20:03 UTC, Aaronontheweb reviewed
Detailed my changes

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.API.Tests/verify/CoreAPISpec.ApproveCluster.DotNet.verified.txt
> +    [System.ObsoleteAttribute("No longer used as of Akka.NET v1.5.2")]
`AutoDowning` is now obsolete - it was a bad idea anyway.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/contrib/cluster/Akka.Cluster.Tools.Tests/Singleton/ClusterSingletonConfigSpec.cs
> +            clusterSingletonManagerSettings.RemovalMargin.TotalSeconds.ShouldBe(20); // now 20 due to default SBR settings
`RemovalMargin` now uses SBR default value of 20 seconds (this is where the value is computed from.)

2023-04-04 20:03 UTC, Aaronontheweb commented on docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
> +## Upgrading to Akka.NET v1.5.2
Upgrade advisories for this PR as well as https://github.com/akkadotnet/akka.net/issues/6389

2023-04-04 20:03 UTC, Aaronontheweb commented on docs/community/whats-new/akkadotnet-v1.5-upgrade-advisories.md
> +To disable the default Akka.Cluster downing provider, simply configure the following in your HOCON:
Duplicated this section from the Split Brain Resolver page - explains how to disable the new default SBR, since I'm fairly certain we'll get a question about that in the future.

2023-04-04 20:03 UTC, Aaronontheweb commented on docs/articles/clustering/split-brain-resolver.md
> +> As of Akka.NET v1.5.2, the `keep-majority` split brain resolution strategy is now enabled by default. This should be acceptable for the majority of Akka.Cluster users, but please read on.
Tried to make it clear that there is now a default SBR enabled.

2023-04-04 20:03 UTC, Aaronontheweb commented on docs/articles/clustering/split-brain-resolver.md
> +### Disabling the Default Downing Provider
Add section explaining how to disable default downing provider.

2023-04-04 20:03 UTC, Aaronontheweb commented on docs/articles/clustering/split-brain-resolver.md
> +* `keep-majority` **(default)**
Again, tried to make it clear what the defaults are here.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
> +            settings.DowningProviderType.Should().Be<SplitBrainResolverProvider>();
Assert the new default SBR settings.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster.Tests/ClusterConfigSpec.cs
> +        public void Cluster_should_allow_disabling_of_default_DowningProvider()
Validate that the new defaults can be disabled / overridden.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster/Cluster.cs
> +            if (Settings.AutoDownUnreachableAfter != null)
If a user still has `akka.cluster.auto-down-unreachable-after` enabled, we raise a warning to let them know that this settings is now being ignored and `keep-majority` is going to be used instead.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster/ClusterDaemon.cs
> -            public override bool Equals(object obj)
This `Equals` method is not necessary and was generating a build warning. Removed it.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster/ClusterSettings.cs
> +            DowningProviderType = !string.IsNullOrEmpty(downingProviderClassName) ? Type.GetType(downingProviderClassName, true) : typeof(NoDowning);
Disabled loading of `AutoDowning` here as it's no longer supported.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster/Configuration/Cluster.conf
> -    auto-down-unreachable-after = off
Removed `auto-down-unreachable-after` setting from the base config.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Cluster/Configuration/Cluster.conf
> +    downing-provider-class = "Akka.Cluster.SBR.SplitBrainResolverProvider, Akka.Cluster"
This is the major change - the default SBR.

2023-04-04 20:03 UTC, Aaronontheweb commented on src/core/Akka.Remote.TestKit/MultiNodeSpec.cs
> +                        cluster.downing-provider-class = """" #disable SBR by default
Backwards compat for the MNTR - keep the SBR disabled by default. Most tests probably don't want the SBR running anyway unless they explicitly enable it.

2023-04-04 20:32 UTC, Aaronontheweb commented on src/core/Akka.Cluster/ClusterDaemon.cs
> -            public override bool Equals(object obj)
Welp, tests are failing now that I've removed this - guess I'm going to have to add it back cc @Arkatufus

2023-04-05 13:55 UTC, Aaronontheweb commented on src/core/Akka.Cluster/ClusterDaemon.cs
> -            public override bool Equals(object obj)
This has been fixed.

2023-04-05 14:47 UTC, Aaronontheweb commented on src/core/Akka.Cluster/ClusterSettings.cs
> +            if (AutoDownUnreachableAfter == default(TimeSpan)) // need to restore correct defaults now that it's been deleted from HOCON file
This is a work-around needed to restore the "correct" defaults for `AutoDownUnreachableAfter` now that it's no longer included in the default `cluster.conf` file.

2023-04-05 15:13 UTC, Aaronontheweb commented on src/contrib/cluster/Akka.Cluster.Sharding.Tests.MultiNode/ClusterShardingSpec.cs
> +                akka.cluster.downing-provider-class = ""Akka.Cluster.SBR.SplitBrainResolverProvider, Akka.Cluster""
This spec previously relied on `auto-down-unreachable-after` - in order to make it pass again we needed to:

* Enable the SBR
* Set the `akka.cluster.split-brain-resolver.stable-after` to the lowest possible value (must be > 0.0s)
* Set the `akka.cluster.down-removal-margin` to the lowest possible value (must be > 0.0s)

2023-04-05 15:42 UTC, Arkatufus requested changes
Just have a question

2023-04-05 15:42 UTC, Arkatufus commented on docs/articles/clustering/split-brain-resolver.md
> +akka.cluster.downing-provider-class = ""
Question, since we removed AutoDowning, what will happen if a user turn SBR off?

2023-04-05 16:17 UTC, Aaronontheweb commented on docs/articles/clustering/split-brain-resolver.md
> +akka.cluster.downing-provider-class = ""
Answered in chat - nothing. AutoDowning was never enabled by default and we strongly discouraged users from ever enabling it. If the default SBR is disabled Akka.Cluster behaves exactly like it does today: unreachable nodes stay unreachable until downed manually by `pbm` or some other process.

2023-04-05 16:49 UTC, Arkatufus approved these changes

2023-04-05 17:00 UTC, Aaronontheweb commented
Local test runner appears to be crashing on Windows - I'll re-run it once the rest of the PR completes testing.

```
Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..

 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.

```

# Do not press `Update Branch`

2023-04-05 19:46 UTC, merged