[CS0618][Stage] Warning Disable
akkadotnet/akka.net pull request #6676
Opened 2023-04-25 14:41 UTC by eaba

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] This change follows the [Akka.NET API Compatibility Guidelines](https://getakka.net/community/contributing/api-changes-compatibility.html).
* [x] This change follows the [Akka.NET Wire Compatibility Guidelines](https://getakka.net/community/contributing/wire-compatibility.html).

2023-04-25 15:09 UTC, Aaronontheweb reviewed
Left a question

2023-04-25 15:09 UTC, Aaronontheweb commented on src/core/Akka.Streams/Implementation/Stages/Stages.cs
>      public interface ISymbolicStage<in TIn, out TOut> : IStage<TIn, TOut>
Is it `IStage` that is obsolete? Any reason why it was marked as Obsolete (in the `Reason` field?)

2023-04-26 07:55 UTC, eaba commented on src/core/Akka.Streams/Implementation/Stages/Stages.cs
>      public interface ISymbolicStage<in TIn, out TOut> : IStage<TIn, TOut>
https://github.com/akkadotnet/akka.net/blob/b688e5cf2e786f582e7e440210c194b6161f8b98/src/core/Akka.Streams/Stage/Stage.cs#L33-L36

2023-04-26 20:41 UTC, Aaronontheweb commented on src/core/Akka.Streams/Implementation/Stages/Stages.cs
>      public interface ISymbolicStage<in TIn, out TOut> : IStage<TIn, TOut>
@eaba so let's use `GraphStage` instead of `IStage`, rather than disable the warning.

2023-04-26 20:41 UTC, Aaronontheweb requested changes
Need to follow the warning's advice rather than disable it.

2023-04-26 20:42 UTC, Aaronontheweb approved these changes
LGTM

2023-04-26 20:42 UTC, Aaronontheweb commented on src/core/Akka.Streams/Implementation/Stages/Stages.cs
>      public interface ISymbolicStage<in TIn, out TOut> : IStage<TIn, TOut>
Ah, I think I see what the issue is here - this is an interface not a class - therefore it can't be fixed via inheriting from GraphStage, got it.

2023-04-26 20:42 UTC, merged