[Doc] Upgrade to `Docfx 2.67.0`
akkadotnet/akka.net pull request #6738
Opened 2023-05-07 14:15 UTC by eaba

Fixes #6666

## Changes

- remove `docfx.console`

## Checklist

For significant changes, please ensure that the following have been completed (delete if not relevant):

* [x] I have [reviewed my own pull request](https://getakka.net/community/contributing/index.html#review-your-own-pull-requests).

2023-05-07 14:21 UTC, eaba reviewed
Removed `docfx.console` @Aaronontheweb

2023-05-07 14:21 UTC, eaba commented on build.fsx
>                  |> append ("--warningsAsErrors")
Unknown option 'Docfx_Git_Timeout'

2023-05-07 14:21 UTC, eaba commented on build.ps1
Docfx 2.67.0

2023-05-07 14:21 UTC, eaba commented on build.ps1
>  }
dotnet tool install

2023-05-07 14:21 UTC, eaba commented on docs/docfx.json
> +        "Docfx_Git_Timeout": 30000
I did `Docfx_Git_Timeout` for build

2023-05-07 14:24 UTC, eaba commented on docs/docfx.json
> +        "Docfx_Git_Timeout": 30000
Is this right? @Aaronontheweb

2023-05-07 15:07 UTC, eaba commented
Local.....
![image](https://user-images.githubusercontent.com/8049896/236685724-6957fd31-805b-419c-8359-9edbff609484.png)

2023-05-07 15:33 UTC, eaba commented
https://github.com/dotnet/docfx/issues/8676

2023-05-08 14:04 UTC, Aaronontheweb commented on docs/docfx.json
> +        "Docfx_Git_Timeout": 30000
You tell me :p

2023-05-08 14:06 UTC, Aaronontheweb commented
> [dotnet/docfx#8676](https://github.com/dotnet/docfx/issues/8676)

I'd work around this issue and do a local install like how we do for Incrementalist:

https://github.com/akkadotnet/akka.net/blob/c402cc7225a334614d75c5d9039afb01e446c79f/build.ps1#L105-L113

We make zero attempts at updating the existing tool - users have to delete their `tools` folder in the root of the Akka.NET repo and re-run the install script to upgrade. I'd do that.

2023-05-08 14:07 UTC, Aaronontheweb commented on build.ps1
> +$DocfxExePath = Join-Path $ToolPath "docfx.exe"
need a sub-folder for this

2023-05-09 13:29 UTC, Aaronontheweb requested changes

2023-05-09 13:29 UTC, Aaronontheweb commented on build.fsx
> +                //|> append ("--Docfx_Git_Timeout")
Aren't these the settings we're trying to turn on? And don't we want to keep `--warningsAsErrors`?

2023-05-09 13:30 UTC, Aaronontheweb reviewed
Looks like you disabled the DocFx settings we wanted to turn on in this PR and `warningsAsErrors`

2023-05-09 13:30 UTC, Aaronontheweb reviewed
Looks like you disabled the DocFx settings we wanted to turn on in this PR and `warningsAsErrors`

2023-05-09 13:36 UTC, eaba commented on build.fsx
> +                //|> append ("--Docfx_Git_Timeout")
If I turn it back, is not working. Let me try another way @Aaronontheweb

2023-05-09 15:51 UTC, Aaronontheweb commented on docs/docfx.json
> +        "Docfx_Git_Timeout": 30000
Ah ok, so this is set inside the `docfx.json` now instead of FAKE. Makes sense.

2023-05-09 15:51 UTC, Aaronontheweb approved these changes
LGTM

2023-05-09 15:52 UTC, Aaronontheweb approved these changes
LGTM

2023-05-09 16:23 UTC, merged