[FIX][pre][code] CSS problem
akkadotnet/akka.net pull request #6756
Opened 2023-05-10 20:53 UTC by eaba

2023-05-11 12:02 UTC, eaba commented
I want to create another branch for `footer`? @Aaronontheweb

2023-05-11 12:05 UTC, Aaronontheweb commented
> I want to create another branch for `footer`? @Aaronontheweb

that should be fine. Can you post screenshots of the new homepage here?

2023-05-11 12:13 UTC, eaba commented
**before**:

![image](https://github.com/akkadotnet/akka.net/assets/8049896/443f8575-a65e-48f2-ae5b-0f72101fbcf4)

 **after**:

![image](https://github.com/akkadotnet/akka.net/assets/8049896/e18a669b-5a4c-4272-826a-c4f697feb7e2)

2023-05-11 12:25 UTC, Aaronontheweb commented
> I want to create another branch for `footer`? @Aaronontheweb

Based on our convo it in Slack, sounds like problems with the footer are the result of this PR. That needs to be fixed too before we can merge this.

2023-05-11 12:29 UTC, eaba commented
https://getakka.net/api/Akka.Cluster.TestKit.html https://getakka.net/api/Akka.Actor.Internal.html

maybe just increase the height? Footer new PR?

2023-05-11 18:15 UTC, eaba commented
![image](https://github.com/akkadotnet/akka.net/assets/8049896/ea806019-8745-4e3f-858d-1e344d579fcd)

2023-05-12 12:13 UTC, Aaronontheweb requested changes
Can you please explain why you made these changes?

2023-05-12 12:13 UTC, Aaronontheweb commented on docs/template/styles/docfx.js
> -        // $("footer").fadeOut();
@eaba this was disabled so the footer would stay persistent at the bottom of the site. Why did you add it back?

2023-05-12 12:13 UTC, Aaronontheweb requested changes
Can you please explain why you made these changes?

2023-05-12 12:48 UTC, eaba commented
I will revert it. First, I thought that the new changes are docfx v2.67.0. Second, @Arkatufus give me idea yesterday, I tried it, not the problem. Removing `footer` solved it!

2023-05-12 13:37 UTC, Aaronontheweb commented
> I will revert it. First, I thought that the new changes are docfx v2.67.0. Second, @Arkatufus give me idea yesterday, I tried it, not the problem. Removing `footer` solved it!

thanks @eaba - I'll try running this again locally.

2023-05-15 14:06 UTC, Aaronontheweb commented on docs/docfx.json
> -        "noLangKeyword": false,
Need to add all three of these deleted settings back

2023-05-15 14:07 UTC, Aaronontheweb requested changes
LGTM, provided that we add the required `docfx.json` settings back

2023-05-15 14:09 UTC, Aaronontheweb approved these changes

2023-05-15 14:38 UTC, merged