Add Cluster.Sharding DData backward compatibility wire format mode
akkadotnet/akka.net pull request #6775
Opened 2023-05-25 21:22 UTC by Arkatufus

Fixes #6704

## Changes

- Add `akka.cluster.sharding.distributed-data.backward-compatible-wire-format` to allow v1.5 to talk with v1.4
- Add DData hack to convert v1.4 to v1.5 data structure serialization

2023-05-26 09:53 UTC, Aaronontheweb requested changes
Do we need to add a simple regression test to the sharding message serializer to ensure that this fix works?

2023-05-26 13:08 UTC, Arkatufus commented
The fix was not in the sharding serializer, its in the DData `LWWRegister<T>` serializer

2023-05-26 13:12 UTC, Aaronontheweb commented
@Arkatufus  is it feasible to unit test this fix?

2023-05-26 13:26 UTC, Arkatufus commented
Well, the target class does not exist in v1.5 binary anymore, testing would require a v1.4 binary protobuf loaded from disk and see if the serializer can deserialize it?

2023-05-26 13:30 UTC, Arkatufus commented
Actually, we can probably test the `ToProto` methods to see if it generates the correct `TypeInfo`, ~~but that would require us to change the method from private to internal~~

2023-05-26 14:22 UTC, Arkatufus commented
Done

2023-05-29 14:14 UTC, Aaronontheweb approved these changes
LGTM

2023-05-29 14:14 UTC, Aaronontheweb commented on src/contrib/cluster/Akka.DistributedData/Serialization/ReplicatedDataSerializer.cs
> +            if(_backwardCompatWireFormat && pLww.TypeInfo.TypeName == "Akka.Cluster.Sharding.ShardCoordinator+CoordinatorState, Akka.Cluster.Sharding")
LGTM

2023-05-29 14:14 UTC, merged